//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceInvadersRemake.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class KeyboardConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static KeyboardConfig defaultInstance = ((KeyboardConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new KeyboardConfig())));
        
        public static KeyboardConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::Microsoft.Xna.Framework.Input.Keys Left {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Left"]));
            }
            set {
                this["Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public global::Microsoft.Xna.Framework.Input.Keys Right {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Right"]));
            }
            set {
                this["Right"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Space")]
        public global::Microsoft.Xna.Framework.Input.Keys Fire {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Fire"]));
            }
            set {
                this["Fire"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Up")]
        public global::Microsoft.Xna.Framework.Input.Keys Up {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Up"]));
            }
            set {
                this["Up"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Down")]
        public global::Microsoft.Xna.Framework.Input.Keys Down {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Down"]));
            }
            set {
                this["Down"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Escape")]
        public global::Microsoft.Xna.Framework.Input.Keys Back {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Back"]));
            }
            set {
                this["Back"] = value;
            }
        }
    }
}
