//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceInvadersRemake.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class XBoxControllerConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static XBoxControllerConfig defaultInstance = ((XBoxControllerConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new XBoxControllerConfig())));
        
        public static XBoxControllerConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DPadLeft")]
        public global::Microsoft.Xna.Framework.Input.Buttons Left {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Buttons)(this["Left"]));
            }
            set {
                this["Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DPadRight")]
        public global::Microsoft.Xna.Framework.Input.Buttons Right {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Buttons)(this["Right"]));
            }
            set {
                this["Right"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::Microsoft.Xna.Framework.Input.Buttons Fire {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Buttons)(this["Fire"]));
            }
            set {
                this["Fire"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DPadUp")]
        public global::Microsoft.Xna.Framework.Input.Buttons Up {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Buttons)(this["Up"]));
            }
            set {
                this["Up"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DPadDown")]
        public global::Microsoft.Xna.Framework.Input.Buttons Down {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Buttons)(this["Down"]));
            }
            set {
                this["Down"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B")]
        public global::Microsoft.Xna.Framework.Input.Buttons Back {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Buttons)(this["Back"]));
            }
            set {
                this["Back"] = value;
            }
        }
    }
}
