//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.235
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceInvadersRemake.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpaceInvadersRemake.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Space Invaders Remake ähnelt.
        /// </summary>
        public static string Game_Titel {
            get {
                return ResourceManager.GetString("Game_Titel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audio ähnelt.
        /// </summary>
        public static string Label_Audio {
            get {
                return ResourceManager.GetString("Label_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AUDIO OPTIONS ähnelt.
        /// </summary>
        public static string Label_AUDIOOPTIONS {
            get {
                return ResourceManager.GetString("Label_AUDIOOPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Credits ähnelt.
        /// </summary>
        public static string Label_Credits {
            get {
                return ResourceManager.GetString("Label_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Effect Volume ähnelt.
        /// </summary>
        public static string Label_EffectVolume {
            get {
                return ResourceManager.GetString("Label_EffectVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fullscreen ähnelt.
        /// </summary>
        public static string Label_Fullscreen {
            get {
                return ResourceManager.GetString("Label_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Highscore ähnelt.
        /// </summary>
        public static string Label_Highscore {
            get {
                return ResourceManager.GetString("Label_Highscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Master Volume ähnelt.
        /// </summary>
        public static string Label_MasterVolume {
            get {
                return ResourceManager.GetString("Label_MasterVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Music Volume ähnelt.
        /// </summary>
        public static string Label_MusicVolume {
            get {
                return ResourceManager.GetString("Label_MusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Off ähnelt.
        /// </summary>
        public static string Label_OFF {
            get {
                return ResourceManager.GetString("Label_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On ähnelt.
        /// </summary>
        public static string Label_ON {
            get {
                return ResourceManager.GetString("Label_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        public static string Label_Options {
            get {
                return ResourceManager.GetString("Label_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quit ähnelt.
        /// </summary>
        public static string Label_Quit {
            get {
                return ResourceManager.GetString("Label_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quit Game ähnelt.
        /// </summary>
        public static string Label_QuitGame {
            get {
                return ResourceManager.GetString("Label_QuitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resolution ähnelt.
        /// </summary>
        public static string Label_Resolution {
            get {
                return ResourceManager.GetString("Label_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Return To Game ähnelt.
        /// </summary>
        public static string Label_ReturnToGame {
            get {
                return ResourceManager.GetString("Label_ReturnToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Game ähnelt.
        /// </summary>
        public static string Label_StartGame {
            get {
                return ResourceManager.GetString("Label_StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Video ähnelt.
        /// </summary>
        public static string Label_Video {
            get {
                return ResourceManager.GetString("Label_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VIDEO OPTIONS ähnelt.
        /// </summary>
        public static string Label_VIDEOOPTIONS {
            get {
                return ResourceManager.GetString("Label_VIDEOOPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chuck Norris ähnelt.
        /// </summary>
        public static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ~~~~~~~~~~~~~~~~~~~~~~~~~
        ///~ Space Invaders Remake ~
        ///~~~~~~~~~~~~~~~~~~~~~~~~~
        ///           ~preAlpha~
        ///
        ///An diesem Projekt waren beteiligt:
        ///     Anjela Mayer
        ///     Christian Klotz
        ///     Dominik Sauter
        ///     Dominik Schaufelberger
        ///     Steffen Stehmann
        ///     Tobias Bast
        ///
        ///Wir danken einfach allen! ähnelt.
        /// </summary>
        public static string Text_Credits {
            get {
                return ResourceManager.GetString("Text_Credits", resourceCulture);
            }
        }
    }
}
