//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceInvadersRemake.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class GameConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static GameConfig defaultInstance = ((GameConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GameConfig())));
        
        public static GameConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Keyboard")]
        public global::SpaceInvadersRemake.Settings.SupportedInputEnum Input {
            get {
                return ((global::SpaceInvadersRemake.Settings.SupportedInputEnum)(this["Input"]));
            }
            set {
                this["Input"] = value;
            }
        }
    }
}
