//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceInvadersRemake.Settings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpaceInvadersRemake.Settings.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Label_Audio {
            get {
                return ResourceManager.GetString("Label_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUDIO OPTIONS.
        /// </summary>
        public static string Label_AUDIOOPTIONS {
            get {
                return ResourceManager.GetString("Label_AUDIOOPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Label_Credits {
            get {
                return ResourceManager.GetString("Label_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect Volume.
        /// </summary>
        public static string Label_EffectVolume {
            get {
                return ResourceManager.GetString("Label_EffectVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string Label_Fullscreen {
            get {
                return ResourceManager.GetString("Label_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highscore.
        /// </summary>
        public static string Label_Highscore {
            get {
                return ResourceManager.GetString("Label_Highscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Volume.
        /// </summary>
        public static string Label_MasterVolume {
            get {
                return ResourceManager.GetString("Label_MasterVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Volume.
        /// </summary>
        public static string Label_MusicVolume {
            get {
                return ResourceManager.GetString("Label_MusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Label_OFF {
            get {
                return ResourceManager.GetString("Label_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string Label_ON {
            get {
                return ResourceManager.GetString("Label_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Label_Options {
            get {
                return ResourceManager.GetString("Label_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Label_Quit {
            get {
                return ResourceManager.GetString("Label_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Game.
        /// </summary>
        public static string Label_QuitGame {
            get {
                return ResourceManager.GetString("Label_QuitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string Label_Resolution {
            get {
                return ResourceManager.GetString("Label_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return To Game.
        /// </summary>
        public static string Label_ReturnToGame {
            get {
                return ResourceManager.GetString("Label_ReturnToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        public static string Label_StartGame {
            get {
                return ResourceManager.GetString("Label_StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Label_Video {
            get {
                return ResourceManager.GetString("Label_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIDEO OPTIONS.
        /// </summary>
        public static string Label_VIDEOOPTIONS {
            get {
                return ResourceManager.GetString("Label_VIDEOOPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~~~~~~~~~~~~~~~~~~~~~~~~~
        ///~ Space Invaders Remake ~
        ///~~~~~~~~~~~~~~~~~~~~~~~~~
        ///           ~preAlpha~
        ///
        ///An diesem Projekt waren beteiligt:
        ///     Anjela Mayer
        ///     Christian Klotz
        ///     Dominik Sauter
        ///     Dominik Schaufelberger
        ///     Steffen Stehmann
        ///     Tobias Bast
        ///
        ///Wir danken einfach allen!.
        /// </summary>
        public static string Text_Credits {
            get {
                return ResourceManager.GetString("Text_Credits", resourceCulture);
            }
        }
    }
}
